---
id: Argv
name: Argv
full: Command-line argument parsing library
description: >
  Classes for parsing command line arguments with various actions, providing
  help, grouping options, and more.
list: dev
